"""Tool base class + result model.

Each tool declares:
- name: str
- description: str
- args_model: pydantic BaseModel — schema for arguments
- _run(args): actual execute

`BaseTool.execute()` is a facade: it validates args via pydantic, then calls `_run()`.
Subclasses override `_run()` ONLY. They must not touch `execute()`.
"""

from __future__ import annotations

from abc import ABC, abstractmethod

from pydantic import BaseModel, ValidationError


class ToolResult(BaseModel):
    """Result of a single tool execution."""

    output: str
    ok: bool = True


class BaseTool(ABC):
    """Base class for every tool."""

    name: str
    description: str
    args_model: type[BaseModel]

    @abstractmethod
    def _run(self, args: BaseModel) -> ToolResult:
        """Execute with validated args. Overridden by subclasses.

        Args:
            args: Instance of self.args_model that has passed validation.
        """
        ...

    def execute(self, arguments: dict) -> ToolResult:
        """Validate arguments via args_model, then call _run.

        Args:
            arguments: raw dict from the LLM. May have the wrong shape.

        Returns:
            ToolResult(ok=False) if validation fail.
            ToolResult từ _run() if OK.
        """
        try:
            args = self.args_model.model_validate(arguments)
        except ValidationError as e:
            return ToolResult(
                output=f"Invalid arguments for tool '{self.name}': {e}",
                ok=False,
            )
        return self._run(args)

    @property
    def input_schema(self) -> dict:
        """JSON schema for LLM function calling. Auto-generated by pydantic."""
        return self.args_model.model_json_schema()
